name: photoviewer
description: A random photo viewing app

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  http: ^0.13.4
  flutter_dotenv: ^5.0.2
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  freezed: ^1.1.0
  freezed_annotation: ^1.1.0
  build_runner: ^2.1.8
  equatable: ^2.0.3
  mockito: ^5.1.0
  #Explicitly defined to fix versioning issue 
  analyzer: ^2.8.0
  meta: ^1.7.0

flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/

  fonts:
    - family: DMSans
      fonts:
        - asset: assets/DMSans-Medium.ttf
